### ISSUE TITLE
Update to DWJ CBC Page Breaks Loading of Extension

### ISSUE THREAD

**Issue by cepedamarc** [BryanCuneo/cb-calc-assistant#1]
DWJ edited the page. Manifest needs update to reflect the new string

698e84f8585fe043d87a995293167e0c

**Comment by cepedamarc** [comment]
See PR https://github.com/BryanCuneo/cb-calc-assistant/pull/3

**Comment by 2f1k** [comment]
Thank you. i modified the manfest.json on local in the extension sirectory but it is not working. May be the frames are not read correctly. Perhaps the all_frames attribute.. IDK. BTW Thank you

**Comment by cepedamarc** [comment]
So the patch isn't working for you on your local? Strange.

**Comment by BryanCuneo** [comment]
Closing all current issues due to add-on deprecation. DWJ has released v2 of his calculator which includes a build-sharing feature!
